version: "3.9"

services:
  next-app:
    container_name: feed-app
    build:
#      context: ./feed-app
      dockerfile: dev.Dockerfile
    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: dev
      NEXT_PUBLIC_ENV_VARIABLE: dev

    # Set environment variables based on the .env file
    env_file:
      - .env.local
    volumes:
      - ./:/app
    restart: always
    ports:
      - "3000:3000"
    networks:
      - feed-parser-net

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  traefik-public:
    external: true
  feed-parser-net:
    name: feed-parser-net